insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('136 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('138 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('140 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('142 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('144 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('146 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('148 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('150 N ParkRidge Rd', 'Bloomington', 'Indiana');
insert into DEMO.ADDRESSES (STREET_ADDRESS, CITY, STATE) values ('152 N ParkRidge Rd', 'Bloomington', 'Indiana');